spring.application.name=game-expert

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3309/game_expert}
spring.datasource.username=${DB_USERNAME:game_user}
spring.datasource.password=${DB_PASSWORD:game_password}
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}